### ISSUE TITLE
Recover password "done" button looks disabled

### ISSUE THREAD

**Issue by frankely** [chaynHQ/soulmedicine#147]
I believe this is not a big deal however for picky users like me this button seemed like if it were disabled so probably making it less transparent could remove that confusion.

<img width="447" alt="Screen Shot 2019-11-13 at 2 15 13 PM" src="https://user-images.githubusercontent.com/653489/68809354-9793fe00-0620-11ea-84b1-edc806706b19.png">

**Comment by sophieheb** [comment]
Thanks for bringing this up @frankely 

We're currently considering redesigning our sign in process. Do you mind if we ask you again in a few weeks for your opinion again?

**Comment by frankely** [comment]
Sounds good! let me know when you need me again!
