### ISSUE TITLE
Link Hover Color Makes Text Disappear

### ISSUE THREAD

**Issue by hereticaneue** [chaynHQ/soulmedicine#148]
When hovering over "Chayn" in the "Powered by Chayn" banner across the bottom of the [home page](https://soulmedicine.io/), the word "Chayn" gets lost. The hover color for the hyperlinks is almost the exact same shade of pink as the background color. (I understand that this is the hover color for all the hyperlinks on the page, but it feels like an accessibility issue to have the link basically disappear upon hover).
<img width="535" alt="SoulMedicine_LinkHoverColor" src="https://user-images.githubusercontent.com/45669137/70087022-1c978500-15d9-11ea-92fc-321d40b8787a.png">

**Comment by sophieheb** [comment]
Thanks for spotting! This is fixed now, so when you hover it changes to our beige colour instead.
