### ISSUE TITLE
language of document is not identified

### ISSUE THREAD

**Issue by thekuiperbelt** [chaynHQ/soulmedicine#149]
Example page: https://soulmedicine.io/en/pathways/how-to-manage-your-money

Why It Matters: Identifying the language of the page allows screen readers to read the content in the appropriate language. It also facilitates automatic translation of content.

How to Fix It: Identify the document language using the <html lang> attribute `<html lang="en">`

**Comment by knksmith57** [comment]
additional details from Lighthouse audit

<img width="717" alt="Screen Shot 2019-12-03 at 14 33 05" src="https://user-images.githubusercontent.com/796851/70087406-e1e21c80-15d9-11ea-8052-34ba8ce2ed87.png">

**Comment by sophieheb** [comment]
Good spot, fix waiting to be merged.

**Comment by sophieheb** [comment]
Merged and fixed here: https://github.com/chaynHQ/soulmedicine/pull/160

Thank you :)
