### ISSUE TITLE
a11y issue: "Got it!" cookie button is very low contrast

### ISSUE THREAD

**Issue by knksmith57** [chaynHQ/soulmedicine#150]
The "Got it!" button used to accept cookies is [very low contrast (1.70)](https://usecontra.st/f7eee3/f4a5a6)

![gotit-cookie-button-low-contrast](https://user-images.githubusercontent.com/796851/70086866-d7735300-15d8-11ea-86e8-d72da016cfae.png)

**Comment by sophieheb** [comment]
Working on a fix.

**Comment by sophieheb** [comment]
Merged and fixed here: https://github.com/chaynHQ/soulmedicine/pull/160

Thank you :)
