### ISSUE TITLE
missing form label

### ISSUE THREAD

**Issue by thekuiperbelt** [chaynHQ/soulmedicine#151]
Example page: https://soulmedicine.io/ar/auth/sign_in

What It Means
A form control does not have a corresponding label.

Why It Matters: If a form control does not have a properly associated text label, the function or purpose of that form control may not be presented to screen reader users. Form labels also provide visible descriptions and larger clickable targets for form controls.

How to Fix It: If a text label for a form control is visible, use the <label> element to associate it with its respective form control. If there is no visible label, either provide an associated label, add a descriptive title attribute to the form control, or reference the label(s) using aria-labelledby. Labels are not required for image, submit, reset, button, or hidden form controls.

**Comment by sophieheb** [comment]
Unfortunately a problem with third party library we use here.

Already detailed in Issue on the repo: https://github.com/firebase/firebaseui-web/issues/639
Fix submitted: https://github.com/firebase/firebaseui-web/pull/655

**Comment by issyl0** [comment]
Looks like this was fixed in FirebaseUI [4.4.0](https://github.com/firebase/firebaseui-web/releases/tag/v4.4.0), and [this app is on 4.5.0](https://github.com/chaynHQ/soulmedicine/blob/14ac17a689d04f3eb01ed2842f2783ee53aa0e08/package.json#L32), so I'll close this.
