### ISSUE TITLE
broken ARIA reference

### ISSUE THREAD

**Issue by thekuiperbelt** [chaynHQ/soulmedicine#153]
Example page: https://soulmedicine.io/en/pathways/diy-online-safety/notes/note-1-how-many-sites-and-services-do-you-use & https://soulmedicine.io/en/profile

What It Means: An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist.

Why It Matters: ARIA labels and descriptions will not be presented if the element referenced does not exist in the page.

How to Fix It: Ensure the element referenced in the aria-labelledby or aria-describedby attribute value is present within the page and presents a proper label or description.

**Comment by sophieheb** [comment]
Working on a fix.
