### ISSUE TITLE
Sign-in & Account Creation Buttons Grayed-Out

### ISSUE THREAD

**Issue by hereticaneue** [chaynHQ/soulmedicine#156]
When filling in the form to create an account or sign in, the buttons still appear "grayed out" even once all of the required information has been filled in. This is confusing and can make the user wonder if they haven't done everything needed in order to proceed.

<img width="379" alt="SoulMedicine_SubmitButtonsGreyedOut" src="https://user-images.githubusercontent.com/45669137/70090070-07bdf000-15df-11ea-87f0-c8d50b2851c2.png">

**Comment by sophieheb** [comment]
We use a 3rd party widget for our sign in that gives us minimal flexibility on this so we won't be able to update this.
