### ISSUE TITLE
Typo - How to cope with stress page

### ISSUE THREAD

**Issue by hereticaneue** [chaynHQ/soulmedicine#157]
Found a couple of typos on the [How to cope with stress](https://soulmedicine.io/en/pathways/how-to-cope-with-stress) page:

"_A lot of experience stress on a day to day basis._" -- Seems like this should read as "A lot of **people** experience stress..." 

"_In this course, we will help you understand how your body and mind reacts to stress,_" -- I think the word "reacts" should be changed to "react".

**Comment by sophieheb** [comment]
Passed to our content team! Thanks for spotting.

**Comment by sophieheb** [comment]
Fixed
