### ISSUE TITLE
UX suggestion: log user out when "leave this site" button is clicked

### ISSUE THREAD

**Issue by knksmith57** [chaynHQ/soulmedicine#158]
When a user clicks the "leave this site" button (which is an awesome UX feature!), they remain signed in. It might be a good idea to also log the user out.

While the browser history will remain intact for that session, if the site is navigated to by a bad actor (ie: the abuser) and the account is still logged in, both the existence of an account and any subscriptions will be viewable. This seems undesirable.

![2019-12-03 15 16 53](https://user-images.githubusercontent.com/796851/70091135-1f967380-15e1-11ea-85ef-01c3e54124c7.gif)

**Comment by sophieheb** [comment]
Working on a fix.

**Comment by sophieheb** [comment]
Merged and fixed here: https://github.com/chaynHQ/soulmedicine/pull/160

Thank you :)
