### ISSUE TITLE
time slot issue

### ISSUE THREAD

**Issue by thekuiperbelt** [chaynHQ/soulmedicine#159]
Example page: https://soulmedicine.io/en/pathways/how-to-open-your-own-bank-account/subscription

Time slot is listed from 23:00 - 25:00, it shoud be 23:00 - 24:00
![image](https://user-images.githubusercontent.com/25801804/70091193-376df780-15e1-11ea-876e-c5c9e8473719.png)

**Comment by sophieheb** [comment]
Fix coming soon!

**Comment by sophieheb** [comment]
Merged and fixed here: https://github.com/chaynHQ/soulmedicine/pull/160

Thank you :)
