### ISSUE TITLE
Upgrade Ruby to 3.1

### ISSUE THREAD

**Issue by tarebyte** [chaynHQ/soulmedicine#308]
The current system is running on [Ruby 2.5.8](https://github.com/chaynHQ/soulmedicine/blob/11d04a0f67a6592938b4b7bdc7fc92ffad9c2327/Gemfile#L6) which reached EOL in April of 2021.

We need to upgrade the system to use Ruby 3.2 to ensure that we are secure and the most up to date that is possible.

Below is the order in which the update is recommended.

- [x] 2.7 (the last of the 2 series)
- [x] 3.0
- [x] 3.1.4 

These should be updated with as few dependencies updated as possible to avoid breaking changes during the upgrade process. Once we're on the latest version of Ruby, we can then look at tackling the Rails framework updates.

**Comment by issyl0** [comment]
https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html

**Comment by tarebyte** [comment]
@issyl0 should we look into upgrading Rails then?

**Comment by issyl0** [comment]
Yeah, I'm planning on looking into that soon!

**Comment by tarebyte** [comment]
I'm adding the `blocked` label until we rollout to Rails 6.

**Comment by issyl0** [comment]
I will wait until #322 is done before I start on Rails 6.

**Comment by tarebyte** [comment]
This has been completed as of https://github.com/chaynHQ/soulmedicine/pull/373
