### ISSUE TITLE
Migrate from Snyk to GitHub's security feature set

### ISSUE THREAD

**Issue by tarebyte** [chaynHQ/soulmedicine#310]
To reduce the number of third party integrations and overhead, we'd like to move from [Snyk](https://snyk.io/) to [GitHub's secuirty feature](https://github.com/features/security).

- [x] Enable Code Scanning Alerts via https://github.com/chaynHQ/soulmedicine/security/code-scanning
- [x] Have an Snyk account admin remove the integration to this organization or repository
- [x] Close outstanding issues and pull requests from Snyk as Dependabot has these covered.

**Comment by issyl0** [comment]
I might be biased since I work on the code scanning product, but the first item here sounds good even if we choose to keep Snyk (which I always spell as Synk first time).

**Comment by seanmarcia** [comment]
I've removed Snyk :)
