### ISSUE TITLE
[Cleanup] Uninstall Travis CI

### ISSUE THREAD

**Issue by tarebyte** [chaynHQ/soulmedicine#311]
As of https://github.com/chaynHQ/soulmedicine/pull/305 we're now officially on GitHub Actions 🎉 

We should remove the Travis CI GitHub App from the organization as it's no longer being used.

**Comment by seanmarcia** [comment]
I tried but we need @eleanorreem to do this.

**Comment by eleanorreem** [comment]
On it!

**Comment by eleanorreem** [comment]
Done ✅
