### ISSUE TITLE
Add link to CONTRIBUTING.md file in README.md 

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/soulmedicine#383]
### Overview
We need to link to the CONTRIBUTING.md file in the README.md so contributors can more easily see the contributing guidelines.

### Action Items
- [ ] Under the title in the "Development and Testing" section in the `README.md`, add the following:
"To make a contribution, please read our Contributing Guidelines in CONTRIBUTING.md"
- [ ] Make sure the sentence above contains a Markdown link to the repo's CONTRIBUTING.md file. 

Please disregard failing tests as we are updating their performance. Thank you!

### Resources/Instructions
- [How to Create Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by kyleecodes** [comment]
Hey @aybeedee thank you for your interest! 
At this time we require contributors to ask for permission in the issue before merging their PR, as stated in the contributing guidelines in the `CONTRIBUTING.md` file. Also, we only allow 1 no-code hacktober issue per person on a single repo, please let me know which one to assign the issue to then we'll get your PR merged! Thanks again.

**Comment by ATREAY** [comment]
hey @kyleecodes, can I work on this issue?

**Comment by kyleecodes** [comment]
@ATREAY thank you for your interest! At this time we only allow 1 no-code issue per contributor. Please let me know if you would like this issue instead! :)

**Comment by kyleecodes** [comment]
Thank you for your interest @ATREAY, you have been assigned. :)

**Comment by ATREAY** [comment]
Hey @kyleecodes, I've made the necessary updates. Could you please take a look when you have a moment?
