### ISSUE TITLE
Link to our Volunteer Info page in our README.md

### ISSUE THREAD

**Issue by kyleecodes** [chaynHQ/soulmedicine#386]
### Overview
Currently, our README links interested volunteers directly to the volunteer form, not to our volunteer info page (which contains the form).  We need the README to link to the [Getting Involved volunteer info page](https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4) instead, similar to how our CONTRIBUTING.md file does.

### Action Items
- [ ] Replace the text in the `README.md` under the Getting Involved section:
If you would like to help Bloom and receive special access to our organization and volunteer opportunities, please get in touch with us to express your interest in volunteering via [this form](https://forms.gle/qXfDdPgJxYwvMmVP7)." 
with the following text:
"If you would like to help Chayn and receive special access to our organization and volunteer opportunities, please visit our Getting Involved page."
- [ ] Make sure the above sentence contains a markdown link to our Getting Involved page: https://www.notion.so/chayn/Get-involved-423c067536f3426a88005de68f0cab19?pvs=4 

Please disregard failing tests as we are updating their performance. Thank you!

### Resources/Instructions
- [How to make Markdown Links](https://www.markdownguide.org/basic-syntax/#links)

**Comment by kyleecodes** [comment]
Hey @aybeedee thank you for your interest! 
At this time we require contributors to ask for permission in the issue before merging their PR, as stated in the contributing guidelines in the `CONTRIBUTING.md` file. Also, we only allow 1 no-code hacktober issue per person on a single repo, please let me know which one to assign the issue to then we'll get your PR merged!

**Comment by aybeedee** [comment]
Hi, apologies for missing the guideline and thanks for the clarification. Will make sure to ask if I contribute again in the future. Kindly assign this one, I've closed the second PR.
